### ISSUE TITLE
Örneği iki dropdown ile uygulama

### ISSUE THREAD

**Issue by udanaDbb** [mehmetcanacik/custom_dropdown_widget#1]
Merhaba hocam öncelikle kolay gelsin. Ülkeleri bir dropdown da ve şehirlere başka bir dropdownda anlık göstermek istiyorum lakin ne denediysem çözemedim sanırım provider sınıfında bir değişiklik yapmamız gerekecek. Bunun nasıl olacağını gösterebilirseniz çok memnun olurum. Teşekkürler iyi çalışmalar.

**Comment by udanaDbb** [comment]
Done

**Comment by mehmetcanacik** [comment]
Merhaba. Eğer bu proje sorunuza cevap olduysa sevindim.

**Comment by udanaDbb** [comment]
Teşekkürler denemelerim sonucu istediğimi uyguladım. Çok güzel bir içerik tebrik ederim.
